Update action.yml

diff --git a/.github/actions/maven-release/action.yml b/.github/actions/maven-release/action.yml
--- a/.github/actions/maven-release/action.yml
+++ b/.github/actions/maven-release/action.yml
@@ -1,99 +1,62 @@
-name: "Maven releases"
-description: "Maven RC, Minor and Patch releases"
+name: "Extract versions from pom"
+description: "Github Actions to Extract version"
 inputs:
   pom-file:
-    description: 'POM file location. Default is at room (pom.xml)'
+    description: 'POM file location. Default is at root (pom.xml)'
     required: false
     default: 'pom.xml'
-  release-minor:
-    description: 'Release minor version'
-    required: false
-    default: 'false'
-  release-patch:
-    description: 'Release patch version'
-    required: false
-    default: 'false'
-  java-version:
-    description: "Java version to Initialize repo"
-    required: false
-    default: "17"
-  distribution:
-    description: "Whether to cache dependencies or not."
-    required: false
-    default: "adopt"
-  gh-token:
-    description: "Github Token to release git tags"
-    required: true
+outputs:
+  pom_current_version:
+    description: "Current version in POM"
+    value: ${{ steps.pom-version.outputs.current_version }}
+  pom_major:
+    description: "Major Version in  POM"
+    value: ${{ steps.pom-version.outputs.major }}
+  pom_minor:
+    description: "Minor Version in  POM"
+    value: ${{ steps.pom-version.outputs.minor }}
+  pom_patch:
+    description: "Patch Version in  POM"
+    value: ${{ steps.pom-version.outputs.patch }}
+  pom_rc:
+    description: "RC number Version in  POM for example 1.0.0-rc.2 would result in 2"
+    value: ${{ steps.pom-version.outputs.rc_ver }}
+  git_full_sha:
+    description: "Git full sha"
+    value: ${{ steps.pom-version.outputs.git_commit }}
+  git_short_sha:
+    description: "Git short sha"
+    value: ${{ steps.pom-version.outputs.git_commit_short }}
 runs:
   using: "composite"
   steps:
-    - name: Validate inputs
-      shell: bash
-      run: |
-        if [ -z "${{ inputs.release-minor }}" ] || [ -z "${{ inputs.release-patch }}" ]; then
-          echo "Cannot release both minor and patch"
-          exit 1
-        fi
-    - name: Initialize Java and Maven
-      uses: dhananjay12/reusable-workflows/.github/actions/init-maven@main
-      with:
-        java-version: ${{ inputs.java-version }}
-        distribution: ${{ inputs.distribution }}
     - name: Current POM version
       id: pom-version
       shell: bash
       run: |
         current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout --file ${{ inputs.pom-file }})
-        current_version=${current_version%-*}
+        echo "current_version=${current_version}" >> $GITHUB_OUTPUT
+        #Remove -SNAPSHOT or -BETA
+        current_version=${current_version%-SNAPSHOT}
+        current_version=${current_version%-BETA}
+        ##SPLIT FROM -RC.
         VERSION_PARTS=(${current_version//-rc./ })
         sem_ver=${VERSION_PARTS[0]}
-        echo "current_sem_ver=${sem_ver}" >> $GITHUB_OUTPUT
-        rc_ver=${VERSION_PARTS[1]}
+        ##SPLIT FROM .
         SEM_VER_PARTS=(${sem_ver//./ })
         echo "major=${SEM_VER_PARTS[0]}" >> $GITHUB_OUTPUT
         echo "minor=${SEM_VER_PARTS[1]}" >> $GITHUB_OUTPUT
         echo "patch=${SEM_VER_PARTS[2]}" >> $GITHUB_OUTPUT
-        echo "rc_ver=${rc_ver}" >> $GITHUB_OUTPUT
-    - name: Git config setup
-      shell: bash
-      run: |
-        git config user.name "GitHub Action"
-        git config user.email "action@github.com"
-    - name: Release RC version
-      if: (!inputs.release-minor && !inputs.release-patch)
-      env:
-        RC_VER: ${{steps.pom-version.outputs.rc_ver}}
-        CURRENT_SEM_VER: ${{steps.pom-version.outputs.current_sem_ver}}
-        GITHUB_TOKEN: ${{ inputs.gh-token }}
-      shell: bash
-      run: |
-        if [ -z ${RC_VER} ]
-          mvn -Darguments=-Dmaven.test.skip release:prepare release:perform  \
-          -DreleaseVersion=${CURRENT_SEM_VER}-rc.$(RC_VER) \
-          -DdevelopmentVersion=${CURRENT_SEM_VER}-rc.$((RC_VER+1))-SNAPSHOT
+        # Extract RC version
+        rc_ver=${VERSION_PARTS[1]}
+        # If RC_VER is empty or not a number, fail
+        if ! [[ "$rc_ver" =~ ^[0-9]+$ ]]; then
+          echo "rc_ver is not a number. Check the RC_VER_PASSED variable is in correct format (eg. 1.0.0-rc.1)."
+          exit 1
         fi
-    - name: Release Minor version
-      if: inputs.release-minor
-      shell: bash
-      env:
-        CURRENT_SEM_VER: ${{steps.pom-version.outputs.current_sem_ver}}
-        MAJOR: ${{steps.pom-version.outputs.major}}
-        MINOR: ${{steps.pom-version.outputs.minor}}
-        GITHUB_TOKEN: ${{ inputs.gh-token }}
-      run: |
-          mvn -Darguments=-Dmaven.test.skip release:prepare release:perform  \
-          -DreleaseVersion=${CURRENT_SEM_VER} \
-          -DdevelopmentVersion=${MAJOR}.$((MINOR+1)).0-rc.0-SNAPSHOT
-    - name: Release Patch version
-      if: inputs.release-patch
-      shell: bash
-      env:
-        CURRENT_SEM_VER: ${{steps.pom-version.outputs.current_sem_ver}}
-        MAJOR: ${{steps.pom-version.outputs.major}}
-        MINOR: ${{steps.pom-version.outputs.minor}}
-        PATCH: ${{steps.pom-version.outputs.patch}}
-        GITHUB_TOKEN: ${{ inputs.gh-token }}
-      run: |
-          mvn -Darguments=-Dmaven.test.skip release:prepare release:perform  \
-          -DreleaseVersion=${MAJOR}.${MINOR}.$((PATCH+1)) \
-          -DdevelopmentVersion=${MAJOR}.${MINOR}.$((PATCH+1))-SNAPSHOT
+        echo "major=${rc_ver}" >> $GITHUB_OUTPUT
+        # Extract git commit hash and short hash 
+        git_commit_short=$(git rev-parse --short HEAD)
+        echo "git_commit_short=${git_commit_short}" >> $GITHUB_OUTPUT
+        git_commit=$(git rev-parse HEAD)
+        echo "git_commit=${git_commit}" >> $GITHUB_OUTPUT
